CREATE SEQUENCE question_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE answer_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE users (
    user_id    NUMBER PRIMARY KEY,          
    username   VARCHAR2(50) NOT NULL UNIQUE, 
    password   VARCHAR2(255) NOT NULL,       
    name       VARCHAR2(100) NOT NULL,       
    phone      VARCHAR2(20) NOT NULL UNIQUE, 
    email      VARCHAR2(150),                
    address    VARCHAR2(500),                
    created_at DATE DEFAULT SYSDATE          
);



CREATE SEQUENCE farms_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE farms (
    farm_id           NUMBER PRIMARY KEY,          
    user_id           NUMBER NOT NULL,            
    farm_name         VARCHAR2(100) NOT NULL,      
    farm_num          NUMBER,                      
    region_l1         VARCHAR2(50),               
    region_l2         VARCHAR2(50),                
    total_area        NUMBER,                      
    first_survey_year NUMBER,                      
    created_at        DATE DEFAULT SYSDATE,        
    CONSTRAINT fk_farm_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);


INSERT INTO users (user_id, username, password, name, phone)
VALUES (0, 'ghost_user', 'system_protected_no_login', '탈퇴회원', '000-0000-0000');
COMMIT;



CREATE SEQUENCE cultivations_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE cultivations (
    cult_id          NUMBER PRIMARY KEY,
    farm_id          NUMBER NOT NULL,       
    item             VARCHAR2(100),
    item_variety     VARCHAR2(100),
    crop_cycle       NUMBER,                
    planting_date    DATE,
    planting_area    NUMBER,
    planting_density NUMBER,
    house_type       VARCHAR2(50),
    house_form       VARCHAR2(50),
    status           VARCHAR2(20) DEFAULT 'active',
    survey_year      NUMBER,             
    created_at       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cult_farm FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);



CREATE SEQUENCE products_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE products (
    product_id      NUMBER PRIMARY KEY,
    cult_id         NUMBER NOT NULL,     
    production_date DATE,                  
    total_quantity  NUMBER,                
    total_sales     NUMBER,                
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT fk_prod_cult FOREIGN KEY (cult_id) REFERENCES cultivations(cult_id)
);




CREATE SEQUENCE seq_env_id START WITH 1 INCREMENT BY 1;
CREATE TABLE environment (
    env_id              NUMBER PRIMARY KEY,
    cult_id             NUMBER NOT NULL,
    measure_time        DATE NOT NULL,
    out_temp            NUMBER(5,2),
    out_wind_direction  NUMBER(5,2),
    out_wind_speed      NUMBER(5,2),
    out_solar_rad       NUMBER(10,2),
    out_acc_solar_rad   NUMBER(15,2),
    rain_detection      NUMBER(1),    
    in_temp             NUMBER(5,2),
    in_humidity         NUMBER(5,2),
    in_co2              NUMBER(10,2),
    soil_temp           NUMBER(5,2),
    created_at          DATE DEFAULT SYSDATE,
    CONSTRAINT fk_env_cult FOREIGN KEY (cult_id) REFERENCES cultivations(cult_id)
);

SELECT ENV_ID, 
       TO_CHAR(MEASURE_TIME, 'YYYY-MM-DD HH24:MI:SS') AS FULL_TIME,
       OUT_TEMP
FROM ENVIRONMENT
WHERE ROWNUM <= 10;

CREATE INDEX idx_env_cult_time ON environment(cult_id, measure_time);

CREATE SEQUENCE growth_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE growth (
    growth_id            NUMBER PRIMARY KEY,   
    cult_id              NUMBER NOT NULL,           
    inspect_date         DATE NOT NULL,            
    plant_num            NUMBER,                  
    branch_num           NUMBER,                    
    plant_height         NUMBER,                      
    growth_length        NUMBER,                    
    leaf_count           NUMBER,                       
    leaf_length          NUMBER,                                  
    leaf_width           NUMBER,                               
    branch_width         NUMBER,                                
    cluster_height       NUMBER,                                 
    cluster_num          NUMBER,                                
    flowers_per_cluster  NUMBER,                                
    blooming_per_cluster NUMBER,                               
    fruits_per_cluster   NUMBER,                                
    blooming_group       NUMBER,                                
    fruiting_group       NUMBER,                                
    remarks              VARCHAR2(1000),                          
    created_at           DATE DEFAULT SYSDATE,     
    CONSTRAINT fk_growth_cult FOREIGN KEY (cult_id) REFERENCES cultivations(cult_id)
);


TRUNCATE TABLE environment;
DROP SEQUENCE seq_env_id;
CREATE SEQUENCE seq_env_id START WITH 1 INCREMENT BY 1 NOCACHE;


SELECT cult_id, 
       COUNT(*) AS 건수, 
       MIN(measure_time) AS 시작일, 
       MAX(measure_time) AS 종료일
FROM environment
GROUP BY cult_id
ORDER BY cult_id;

SELECT CULT_ID, 
       COUNT(*) AS 전체_건수, 
       COUNT(DISTINCT INSPECT_DATE) AS 조사_횟수, -- 실제 조사한 날짜 수
       MIN(INSPECT_DATE) AS 시작일, 
       MAX(INSPECT_DATE) AS 종료일,
       COUNT(DISTINCT PLANT_NUM) AS 조사_개체_수 -- 농가당 몇 그루를 측정했는지
FROM GROWTH
GROUP BY CULT_ID
ORDER BY CULT_ID;


SELECT measure_time, COUNT(*)
FROM environment
WHERE cult_id = 123
GROUP BY measure_time
HAVING COUNT(*) > 1;





CREATE SEQUENCE seq_envcl_id START WITH 1 INCREMENT BY 1;
CREATE TABLE ENV_CLEANED (
    ENVCL_ID NUMBER PRIMARY KEY, 
    ENV_ID NUMBER NOT NULL,                                     
    CULT_ID NUMBER NOT NULL,                                   
    MEASURE_TIME TIMESTAMP NOT NULL,                    
    OUT_TEMP NUMBER(5, 2),
    OUT_WIND_DIRECTION NUMBER(5, 2),
    OUT_WIND_SPEED NUMBER(5, 2),
    OUT_SOLAR_RAD NUMBER(10, 2),
    OUT_ACC_SOLAR_RAD NUMBER(10, 2),
    RAIN_DETECTION NUMBER(1),
    IN_TEMP NUMBER(5, 2),
    IN_HUMIDITY NUMBER(5, 2),
    IN_CO2 NUMBER(10, 2),
    SOIL_TEMP NUMBER(5, 2),
    OUT_ACC_SOLAR_RAD_STATUS NUMBER(1) DEFAULT 0,
    IN_TEMP_STATUS NUMBER(1) DEFAULT 0,
    IN_HUMIDITY_STATUS NUMBER(1) DEFAULT 0,
    IN_CO2_STATUS NUMBER(1) DEFAULT 0,
    MEASURE_DATE DATE,       
    MEASURE_HOUR NUMBER(2),    
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT FK_ENV_ORIGIN FOREIGN KEY (ENV_ID) REFERENCES ENVIRONMENT(ENV_ID)
);

CREATE OR REPLACE TRIGGER TRG_ENV_CLEANED_BI
BEFORE INSERT ON ENV_CLEANED
FOR EACH ROW
BEGIN
  IF :NEW.ENVCL_ID IS NULL THEN
    SELECT seq_envcl_id.NEXTVAL INTO :NEW.ENVCL_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_ENV_CLEANED_CULT ON ENV_CLEANED(CULT_ID);
CREATE INDEX IDX_ENV_CLEANED_TIME ON ENV_CLEANED(MEASURE_TIME);

ALTER TABLE ENV_CLEANED MODIFY (CREATED_AT DEFAULT SYSDATE);
ALTER TABLE ENV_CLEANED MODIFY (CREATED_AT DATE);




CREATE SEQUENCE seq_growcl_id START WITH 1 INCREMENT BY 1;
CREATE TABLE GROW_CLEANED (
    GROWCL_ID           NUMBER PRIMARY KEY,
    GROWTH_ID           NUMBER NOT NULL, 
    CULT_ID             NUMBER NOT NULL,
    INSPECT_DATE        DATE NOT NULL,
    PLANT_NUM           NUMBER,
    BRANCH_NUM          NUMBER,
    PLANT_HEIGHT        NUMBER(10, 2),
    LEAF_COUNT          NUMBER(5),
    LEAF_LENGTH         NUMBER(10, 2),
    LEAF_WIDTH          NUMBER(10, 2),
    BRANCH_WIDTH        NUMBER(10, 2),
    CLUSTER_HEIGHT      NUMBER(10, 2),
    CLUSTER_NUM         NUMBER(5),
    FLOWERS_PER_CLUSTER   NUMBER(10, 2),
    BLOOMING_PER_CLUSTER  NUMBER(10, 2),
    FRUITS_PER_CLUSTER    NUMBER(10, 2),
    BLOOMING_GROUP        NUMBER(10, 4), 
    FRUITING_GROUP        NUMBER(10, 4),
    REMARKS             VARCHAR2(1000),
    ORIGIN_TYPE         NUMBER(1) DEFAULT 0, 
    CREATED_AT          DATE DEFAULT SYSDATE,

    CONSTRAINT FK_GROWTH_ORIGIN FOREIGN KEY (GROWTH_ID) REFERENCES GROWTH(GROWTH_ID)
);

CREATE INDEX IDX_GROWCL_CULT_DATE ON GROW_CLEANED(CULT_ID, INSPECT_DATE);









CREATE TABLE ENV_SUMMARY (
    ENVSU_ID NUMBER PRIMARY KEY,
    CULT_ID NUMBER NOT NULL,
    MEASURE_DATE DATE NOT NULL,
    DAILY_OUT_TEMP NUMBER(10, 2),
    DAILY_ACC_SOLAR NUMBER(10, 2),
    DAILY_RAIN_DETECTION NUMBER(1),
    DAILY_IN_TEMP NUMBER(10, 2),
    DAILY_IN_HUMIDITY NUMBER(10, 2),
    DAILY_IN_CO2 NUMBER(10, 2),
    DAILY_SOIL_TEMP NUMBER(10, 2),
    ACC_TEMP NUMBER(10, 2),
    ACC_SOLAR NUMBER(10, 2),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_ENVSU_ID START WITH 1 INCREMENT BY 1;

INSERT INTO ENV_SUMMARY (
    ENVSU_ID, CULT_ID, MEASURE_DATE, 
    DAILY_OUT_TEMP, DAILY_ACC_SOLAR, DAILY_RAIN_DETECTION,
    DAILY_IN_TEMP, DAILY_IN_HUMIDITY, DAILY_IN_CO2, DAILY_SOIL_TEMP,
    ACC_TEMP, ACC_SOLAR
)
SELECT 
    SEQ_ENVSU_ID.NEXTVAL,
    CULT_ID, M_DATE,
    AVG_OUT_TEMP, TARGET_ACC_SOLAR, MAX_RAIN,
    AVG_IN_TEMP, AVG_IN_HUMIDITY, AVG_IN_CO2, AVG_SOIL_TEMP,
    RUNNING_ACC_TEMP, RUNNING_ACC_SOLAR
FROM (
    WITH DAILY_BASE AS (
        SELECT 
            E.CULT_ID,
            TRUNC(E.MEASURE_DATE) AS M_DATE,
            TRUNC(C.PLANTING_DATE) AS P_DATE,
            AVG(E.OUT_TEMP) AS AVG_OUT_TEMP,
            MAX(CASE WHEN E.MEASURE_HOUR BETWEEN 14 AND 23 THEN E.OUT_ACC_SOLAR_RAD ELSE 0 END) AS TARGET_ACC_SOLAR,
            MAX(E.RAIN_DETECTION) AS MAX_RAIN,
            AVG(E.IN_TEMP) AS AVG_IN_TEMP,
            AVG(E.IN_HUMIDITY) AS AVG_IN_HUMIDITY,
            AVG(E.IN_CO2) AS AVG_IN_CO2,
            AVG(E.SOIL_TEMP) AS AVG_SOIL_TEMP
        FROM ENV_CLEANED E
        LEFT OUTER JOIN CULTIVATIONS C ON E.CULT_ID = C.CULT_ID
        GROUP BY E.CULT_ID, TRUNC(E.MEASURE_DATE), TRUNC(C.PLANTING_DATE)
    ),
    ACCUMULATED_CALC AS (
        SELECT 
            DB.*,
            CASE 
                WHEN DB.M_DATE >= DB.P_DATE THEN 
                    SUM(CASE WHEN DB.M_DATE >= DB.P_DATE THEN DB.AVG_IN_TEMP ELSE 0 END) 
                    OVER (PARTITION BY DB.CULT_ID ORDER BY DB.M_DATE)
                ELSE NULL 
            END AS RUNNING_ACC_TEMP,
            CASE 
                WHEN DB.M_DATE >= DB.P_DATE THEN 
                    SUM(CASE WHEN DB.M_DATE >= DB.P_DATE THEN DB.TARGET_ACC_SOLAR ELSE 0 END) 
                    OVER (PARTITION BY DB.CULT_ID ORDER BY DB.M_DATE)
                ELSE NULL 
            END AS RUNNING_ACC_SOLAR
        FROM DAILY_BASE DB
    )
    SELECT * FROM ACCUMULATED_CALC ORDER BY CULT_ID, M_DATE;
    
    
TRUNCATE TABLE ENV_SUMMARY;
DROP SEQUENCE SEQ_ENVSU_ID;
CREATE SEQUENCE SEQ_ENVSU_ID START WITH 1 INCREMENT BY 1;
);
COMMIT;









INSERT INTO ENV_SUMMARY (
    ENVSU_ID, CULT_ID, MEASURE_DATE, 
    DAILY_OUT_TEMP, DAILY_ACC_SOLAR, DAILY_RAIN_DETECTION,
    DAILY_IN_TEMP, DAILY_IN_HUMIDITY, DAILY_IN_CO2, DAILY_SOIL_TEMP,
    ACC_TEMP, ACC_SOLAR
)
SELECT 
    SEQ_ENVSU_ID.NEXTVAL,
    CULT_ID, M_DATE,
    AVG_OUT_TEMP, TARGET_ACC_SOLAR, MAX_RAIN,
    AVG_IN_TEMP, AVG_IN_HUMIDITY, AVG_IN_CO2, AVG_SOIL_TEMP,
    RUNNING_ACC_TEMP, RUNNING_ACC_SOLAR
FROM (
    WITH DAILY_BASE AS (
        SELECT 
            E.CULT_ID,
            TRUNC(E.MEASURE_DATE) AS M_DATE,
            TRUNC(C.PLANTING_DATE) AS P_DATE,
            AVG(E.OUT_TEMP) AS AVG_OUT_TEMP,
            MAX(CASE WHEN E.MEASURE_HOUR BETWEEN 14 AND 23 THEN E.OUT_ACC_SOLAR_RAD ELSE 0 END) AS TARGET_ACC_SOLAR,
            MAX(E.RAIN_DETECTION) AS MAX_RAIN,
            AVG(E.IN_TEMP) AS AVG_IN_TEMP,
            AVG(E.IN_HUMIDITY) AS AVG_IN_HUMIDITY,
            AVG(E.IN_CO2) AS AVG_IN_CO2,
            AVG(E.SOIL_TEMP) AS AVG_SOIL_TEMP
        FROM ENV_CLEANED E
        LEFT OUTER JOIN CULTIVATIONS C ON E.CULT_ID = C.CULT_ID
        GROUP BY E.CULT_ID, TRUNC(E.MEASURE_DATE), TRUNC(C.PLANTING_DATE)
    ),
    ACCUMULATED_CALC AS (
        SELECT 
            DB.*,
            CASE 
                WHEN DB.M_DATE >= DB.P_DATE THEN 
                    SUM(CASE WHEN DB.M_DATE >= DB.P_DATE THEN DB.AVG_IN_TEMP ELSE 0 END) 
                    OVER (PARTITION BY DB.CULT_ID ORDER BY DB.M_DATE)
                ELSE NULL 
            END AS RUNNING_ACC_TEMP,
            CASE 
                WHEN DB.M_DATE >= DB.P_DATE THEN 
                    SUM(CASE WHEN DB.M_DATE >= DB.P_DATE THEN DB.TARGET_ACC_SOLAR ELSE 0 END) 
                    OVER (PARTITION BY DB.CULT_ID ORDER BY DB.M_DATE)
                ELSE NULL 
            END AS RUNNING_ACC_SOLAR
        FROM DAILY_BASE DB
    )
    SELECT * FROM ACCUMULATED_CALC 
    ORDER BY CULT_ID, M_DATE
);

COMMIT;








UPDATE ENV_SUMMARY 
SET DAILY_ACC_SOLAR = NULL 
WHERE DAILY_ACC_SOLAR = 0;

UPDATE ENV_SUMMARY 
SET ACC_SOLAR = NULL 
WHERE ACC_SOLAR = 0;

COMMIT;






DROP TABLE GROW_SUMMARY;
DROP SEQUENCE SEQ_GROWSU_ID;

CREATE TABLE GROW_SUMMARY (
    GROWSU_ID NUMBER PRIMARY KEY,
    CULT_ID NUMBER NOT NULL,
    INSPECT_DATE DATE NOT NULL,
    GROWTH_DAYS NUMBER,               
    PLANT_NUM NUMBER,
    BRANCH_NUM NUMBER,
    PLANT_HEIGHT NUMBER(10,2),
    GROWTH_LENGTH NUMBER(10,2),       
    LEAF_COUNT NUMBER(5,0),
    LEAF_LENGTH NUMBER(10,2),
    LEAF_WIDTH NUMBER(10,2),
    BRANCH_WIDTH NUMBER(10,2),
    CLUSTER_HEIGHT NUMBER(10,2),
    CLUSTER_NUM NUMBER,
    FLOWERS_PER_CLUSTER NUMBER(10,2),
    BLOOMING_PER_CLUSTER NUMBER(10,2),
    FRUITS_PER_CLUSTER NUMBER(10,2),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_GROWSU_ID START WITH 1 INCREMENT BY 1;


UPDATE CULTIVATIONS 
SET PLANTING_DATE = ADD_MONTHS(PLANTING_DATE, -12) 
WHERE CULT_ID = 203 AND PLANTING_DATE >= '23/01/01';

COMMIT;

ALTER TABLE GROW_SUMMARY ADD (ORIGIN_TYPE NUMBER DEFAULT 0);

COMMENT ON COLUMN GROW_SUMMARY.ORIGIN_TYPE IS '0:원본데이터, 1:보간/보정데이터';


DROP TABLE GROW_CLEANED CASCADE CONSTRAINTS;

COMMENT ON COLUMN GROW_SUMMARY.ORIGIN_TYPE IS '0:원본, 1:보간, 2:날짜오류(정식 전 조사/출하)';


ALTER TABLE GROW_SUMMARY ADD (GROW_ID NUMBER);



DROP TABLE GROW_SUMMARY;
CREATE TABLE GROW_SUMMARY (
    GROWSU_ID      NUMBER NOT NULL,        
    GROW_ID        NUMBER,                 
    CULT_ID        NUMBER NOT NULL,
    INSPECT_DATE   DATE NOT NULL,
    GROWTH_DAYS    NUMBER,
    PLANT_NUM      NUMBER,
    BRANCH_NUM     NUMBER,
    PLANT_HEIGHT   NUMBER(10,2),
    GROWTH_LENGTH  NUMBER(10,2),
    LEAF_COUNT     NUMBER(5,0),
    LEAF_LENGTH    NUMBER(10,2),
    LEAF_WIDTH     NUMBER(10,2),
    BRANCH_WIDTH   NUMBER(10,2),
    CLUSTER_HEIGHT NUMBER(10,2),
    CLUSTER_NUM    NUMBER(14),
    FLOWERS_PER_CLUSTER  NUMBER(10,2),
    BLOOMING_PER_CLUSTER NUMBER(10,2),
    FRUITS_PER_CLUSTER   NUMBER(10,2),
    CREATED_AT     DATE DEFAULT SYSDATE,
    ORIGIN_TYPE    NUMBER DEFAULT 0,
    CONSTRAINT PK_GROW_SUMMARY PRIMARY KEY (GROWSU_ID)
);

COMMENT ON COLUMN GROW_SUMMARY.ORIGIN_TYPE IS '0:원본, 1:보간, 2:날짜오류(정식 전 조사/출하)';


UPDATE ENV_SUMMARY s
SET (s.ACC_TEMP, s.ACC_SOLAR) = (
    SELECT 
        SUM(e.DAILY_IN_TEMP) AS NEW_ACC_TEMP,     
        SUM(e.DAILY_ACC_SOLAR) AS NEW_ACC_SOLAR   
    FROM 
        ENV_SUMMARY e
    JOIN 
        CULTIVATIONS c ON e.CULT_ID = c.CULT_ID
    WHERE 
        e.CULT_ID = 203
        AND e.MEASURE_DATE >= c.PLANTING_DATE  
        AND e.MEASURE_DATE <= s.MEASURE_DATE   
)
WHERE s.CULT_ID = 203;

COMMIT;



CREATE TABLE PROD_SUMMARY (
    PRODSU_ID NUMBER PRIMARY KEY,
    CULT_ID NUMBER NOT NULL,      
    CULT_END_DATE DATE,            
    CULT_TOTAL_QUANTITY NUMBER,    
    CULT_TOTAL_SALES NUMBER,       
    YIELD_PER_AREA NUMBER(10, 2),  
    UNIT_PRICE NUMBER(10, 2),      
    ORIGIN_TYPE NUMBER DEFAULT 0,  
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PRODSU_CULT_ID FOREIGN KEY (CULT_ID) REFERENCES CULTIVATIONS(CULT_ID)
);

CREATE OR REPLACE TRIGGER TRG_PROD_SUMMARY_ID
BEFORE INSERT ON PROD_SUMMARY
FOR EACH ROW
BEGIN
  IF :NEW.PRODSU_ID IS NULL THEN
    SELECT PRODSU_ID_SEQ.NEXTVAL INTO :NEW.PRODSU_ID FROM DUAL;
  END IF;
END;
/






INSERT INTO PROD_SUMMARY (
    CULT_ID, 
    CULT_END_DATE, 
    CULT_TOTAL_QUANTITY, 
    CULT_TOTAL_SALES, 
    YIELD_PER_AREA, 
    UNIT_PRICE, 
    ORIGIN_TYPE
)
SELECT 
    p.CULT_ID,
    MAX(p.PRODUCTION_DATE) AS CULT_END_DATE,
    SUM(p.TOTAL_QUANTITY) AS CULT_TOTAL_QUANTITY,
    SUM(p.TOTAL_SALES) AS CULT_TOTAL_SALES,
    ROUND(SUM(p.TOTAL_QUANTITY) / NULLIF(MAX(c.PLANTING_AREA), 0), 2) AS YIELD_PER_AREA,
    ROUND(SUM(p.TOTAL_SALES) / NULLIF(SUM(p.TOTAL_QUANTITY), 0), 2) AS UNIT_PRICE,
    CASE 
        WHEN MIN(p.PRODUCTION_DATE) < MAX(c.PLANTING_DATE) THEN 2 
        ELSE 0 
    END AS ORIGIN_TYPE
FROM 
    PRODUCTS p
JOIN 
    CULTIVATIONS c ON p.CULT_ID = c.CULT_ID
GROUP BY 
    p.CULT_ID;

COMMIT;



CREATE SEQUENCE SEQ_KAMIS_PRICE START WITH 1 INCREMENT BY 1;
CREATE TABLE KAMIS_TOMATO_PRICE (
    PRICE_ID        NUMBER PRIMARY KEY,      
    PRICE_DATE      DATE NOT NULL,           
    MARKET_NAME     VARCHAR2(50),            
    ITEM_NAME       VARCHAR2(50),            
    TRADE_UNIT      VARCHAR2(50),            
    GRADE           VARCHAR2(20),            
    AVG_PRICE       NUMBER(15, 2),           
    UNIT_KG         NUMBER(10, 2),           
    PRICE_PER_KG    NUMBER(15, 2),           
    GRADE_SCORE     NUMBER(2),              
    CREATED_AT      DATE DEFAULT SYSDATE    
);

CREATE INDEX IDX_TOMATO_DATE ON KAMIS_TOMATO_PRICE(PRICE_DATE);




CREATE TABLE WEATHER_INDEX (
    W_DATE DATE PRIMARY KEY,       -- 날짜 (기준점)
    AVG_TEMP NUMBER(5, 2),         -- 전국 주산지 평균 기온
    SUNSHINE NUMBER(5, 2),         -- 전국 주산지 평균 일조 시간
    RAIN NUMBER(7, 2),             -- 전국 주산지 평균 강수량
    HUMID NUMBER(5, 2),            -- 전국 주산지 평균 상대 습도
    CREATED_AT DATE DEFAULT SYSDATE -- 데이터 생성일
);

COMMENT ON COLUMN WEATHER_INDEX.AVG_TEMP IS '주산지 5곳 평균기온(°C)';
COMMENT ON COLUMN WEATHER_INDEX.SUNSHINE IS '주산지 5곳 합계일조시간(hr)';






ALTER TABLE CULTIVATIONS ADD CULT_NAME VARCHAR2(200 BYTE);
UPDATE CULTIVATIONS c
SET c.CULT_NAME = (
    SELECT f.FARM_NAME || ' ' || c.ITEM || ' ' || c.CROP_CYCLE || '작기'
    FROM FARMS f
    WHERE f.FARM_ID = c.FARM_ID
)
WHERE c.CULT_NAME IS NULL;




ALTER TABLE FARMS ADD (IS_ACTIVE CHAR(1) DEFAULT 'Y');





CREATE SEQUENCE PREDICTION_RESULTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE PREDICTION_RESULTS (
    PREDICTION_ID        NUMBER PRIMARY KEY,
    USER_ID              NUMBER NOT NULL,
    FARM_ID              NUMBER NOT NULL,
    CULT_ID              NUMBER NOT NULL,

    PREDICTION_DATE      DATE DEFAULT SYSDATE NOT NULL,

    ITEM                 VARCHAR2(100 BYTE),
    ITEM_VARIETY         VARCHAR2(100 BYTE),
    CROP_CYCLE           NUMBER,
    PLANTING_DATE        DATE,
    EXPECTED_HARVEST_DATE DATE,

    PLANTING_AREA        NUMBER,
    PLANTING_DENSITY     NUMBER,
    HOUSE_TYPE           VARCHAR2(50 BYTE),
    HOUSE_FORM           VARCHAR2(50 BYTE),

    AVG_DAYS_TO_PEAK_HARVEST NUMBER,
    AVG_YIELD_PER_M2     NUMBER,
    EXPECTED_QUANTITY    NUMBER,
    EXPECTED_PRICE_PER_KG NUMBER,
    EXPECTED_SALES       NUMBER,
    SAMPLE_COUNT         NUMBER,

    LATEST_MARKET_PRICE  NUMBER,
    MARKET_NAME          VARCHAR2(100 BYTE),

    CREATED_AT           DATE DEFAULT SYSDATE,
    UPDATED_AT           DATE DEFAULT SYSDATE
);

ALTER TABLE PREDICTION_RESULTS
ADD CONSTRAINT FK_PRED_USER
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PREDICTION_RESULTS
ADD CONSTRAINT FK_PRED_FARM
FOREIGN KEY (FARM_ID) REFERENCES FARMS(FARM_ID);

ALTER TABLE PREDICTION_RESULTS
ADD CONSTRAINT FK_PRED_CULT
FOREIGN KEY (CULT_ID) REFERENCES CULTIVATIONS(CULT_ID);



ALTER TABLE question ADD user_id NUMBER;
ALTER TABLE answer ADD user_id NUMBER;

ALTER TABLE question
ADD CONSTRAINT fk_question_user
FOREIGN KEY (user_id)
REFERENCES users(user_id);

ALTER TABLE answer
ADD CONSTRAINT fk_answer_user
FOREIGN KEY (user_id)
REFERENCES users(user_id);

UPDATE question SET user_id = 2 WHERE user_id IS NULL;
UPDATE answer SET user_id = 2 WHERE user_id IS NULL;

ALTER TABLE question MODIFY user_id NOT NULL;
ALTER TABLE answer MODIFY user_id NOT NULL;

ALTER TABLE cultivations
ADD virtual_sensor_enabled CHAR(1) DEFAULT 'N';
COMMENT ON COLUMN cultivations.virtual_sensor_enabled IS '가상 환경센서 연결 여부 (Y/N)';

UPDATE CULTIVATIONS
SET VIRTUAL_SENSOR_ENABLED = 'N'
WHERE VIRTUAL_SENSOR_ENABLED IS NULL;
COMMIT;

ALTER TABLE GROW_SUMMARY RENAME COLUMN GROW_ID TO GROWTH_ID;


ALTER TABLE GROW_SUMMARY 
ADD CONSTRAINT FK_GROW_SUMMARY_GROWTH 
FOREIGN KEY (GROWTH_ID) 
REFERENCES GROWTH (GROWTH_ID);

-- ENV_SUMMARY -> CULTIVATIONS 연결
ALTER TABLE ENV_SUMMARY 
ADD CONSTRAINT FK_ENVSUM_CULT 
FOREIGN KEY (CULT_ID) 
REFERENCES CULTIVATIONS (CULT_ID);

-- 1. 재배 정보와 연결
ALTER TABLE ENV_CLEANED 
ADD CONSTRAINT FK_ENVCL_CULT 
FOREIGN KEY (CULT_ID) 
REFERENCES CULTIVATIONS (CULT_ID);

-- 2. 원본 환경 데이터 ID와 연결 (필요한 경우)
ALTER TABLE ENV_CLEANED 
ADD CONSTRAINT FK_ENVCL_ENV 
FOREIGN KEY (ENV_ID) 
REFERENCES ENVIRONMENT (ENV_ID);

ALTER TABLE GROW_SUMMARY 
ADD CONSTRAINT FK_GROW_SUMMARY_CULT 
FOREIGN KEY (CULT_ID) 
REFERENCES CULTIVATIONS (CULT_ID);

-- 핵심 정보들을 필수값으로 변경
ALTER TABLE CULTIVATIONS MODIFY (ITEM NOT NULL);
ALTER TABLE CULTIVATIONS MODIFY (PLANTING_DATE NOT NULL);
ALTER TABLE CULTIVATIONS MODIFY (PLANTING_AREA NOT NULL);
ALTER TABLE CULTIVATIONS MODIFY (CROP_CYCLE NOT NULL);
ALTER TABLE CULTIVATIONS MODIFY (STATUS NOT NULL);
ALTER TABLE CULTIVATIONS MODIFY (HOUSE_TYPE NOT NULL);


-- 온실종류 (HOUSE_TYPE) 제약 조건 추가
ALTER TABLE CULTIVATIONS 
ADD CONSTRAINT CHK_HOUSE_TYPE 
CHECK (HOUSE_TYPE IN ('비닐', '유리', '기타'));

-- 온실유형 (HOUSE_FORM) 제약 조건 추가
ALTER TABLE CULTIVATIONS 
ADD CONSTRAINT CHK_HOUSE_FORM 
CHECK (HOUSE_FORM IN ('연동', '단동', '광폭', '연동양액', '기타'));

ALTER TABLE prediction_results
ADD (
    prediction_source      VARCHAR2(20),
    prediction_confidence  VARCHAR2(20),
    prediction_message     CLOB
);


-- 테이블의 모든 데이터를 삭제 (구조는 유지)
TRUNCATE TABLE SMART.KAMIS_TOMATO_PRICE;
DROP SEQUENCE SEQ_KAMIS_PRICE;
CREATE SEQUENCE SEQ_KAMIS_PRICE START WITH 1 INCREMENT BY 1;

TRUNCATE TABLE SMART.KAMIS_TOMATO_PRICE;
DROP SEQUENCE SEQ_KAMIS_PRICE;
CREATE SEQUENCE SEQ_KAMIS_PRICE START WITH 1 INCREMENT BY 1;
